CREATE TABLE `ddp_stg_safe_product` (
  `product_id` int(11) NOT NULL,
  `pi_sgenno` int(11) DEFAULT NULL,
  PRIMARY KEY (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `frb_es_account` (
  `ACCOUNT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_HOLDER_NAME` varchar(255) DEFAULT NULL,
  `ACCOUNT_TYPE` varchar(255) DEFAULT NULL,
  `CUSTODIAN` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ACCOUNT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
CREATE TABLE `frb_es_account_ips` (
  `ACCOUNT_IPS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` int(11) DEFAULT NULL,
  `IPS_ID` int(11) DEFAULT NULL,
  `EFFECTIVE_DATE` date DEFAULT NULL,
  `EXPIRATION_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ACCOUNT_IPS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;
CREATE TABLE `frb_es_customer` (
  `CUSTOMER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_NAME` varchar(255) DEFAULT NULL,
  `ONBOARDING_DT` datetime DEFAULT NULL,
  `ACCOUNT_NUMBER` varchar(255) DEFAULT NULL,
  `CUSTOMER_TICKER_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CUSTOMER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
CREATE TABLE `frb_es_ips` (
  `IPS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `IPS_GOAL` varchar(4000) DEFAULT NULL,
  `IPS_OBJECTIVES` varchar(4000) DEFAULT NULL,
  `TIME_HORIZON` varchar(255) DEFAULT NULL,
  `RISK_TOLERANCES` varchar(4000) DEFAULT NULL,
  `MODELED_RETURN_PCT` varchar(255) DEFAULT NULL,
  `MODELED_LOSS_PCT` varchar(255) DEFAULT NULL,
  `CURRENT_ASSETS` varchar(255) DEFAULT NULL,
  `ASSET_CLASS_PREFERENCES` varchar(4000) DEFAULT NULL,
  PRIMARY KEY (`IPS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
